This corrects the following warnings in the 64-bit debug build: error C2220: the following warning is treated as an error test\curve25519_selftest.c(393,12): warning C4477: 'printf' : format string '%08X' requires an argument of type 'unsigned int', but variadic argument 2 has type 'const U64'